# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 06ba42b15d07c3266a0f21d5f0b51ad6c7f3d84ade93d8944b1d5bebae791ec5ee0da59c69a34eaa6619bb60c93f9628b4996bebda16a6955a02d48838036e9e

test:
  secret_key_base: ae64f5e4b83bf529c68de1c3bb193a781bad10bc773df87b004f2733314910aeda3292b7d302a8571bac0d992250ebc04e6bab971e66cac1e073ea4c9e0b4e09

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
